### ISSUE TITLE
Two dots always have the same height

### ISSUE THREAD

**Issue by Brianvdb** [bhargavms/DotLoader#6]
I have the strange issue that the 2nd and 3rd two dots are always on the same height. Only happens on my device (OnePlus 3) though. It does not matter how many dots there are, the behaviour is always the same.

Dependency
`compile 'com.github.bhargavms:DotLoader:1.0.3'`

Code in XML

```
<com.bhargavms.dotloader.DotLoader
                android:id="@+id/redeem_verify_loader"
                android:layout_width="wrap_content"
                android:layout_height="80dp"
                android:layout_centerInParent="true"
                app:color_array="@array/redeem_dot_colors"
                app:dot_radius="10dp"
                app:number_of_dots="7" />
```

**Comment by bhargavms** [comment]
does this happen every time you start the app from phone and not android studio?

**Comment by bhargavms** [comment]
Closing this for now as I need more information

**Comment by bhargavms** [comment]
Just discovered this now on my Oneplus2, this only happens when you run the app from adb, something to do with the Animation timer of the framework.
