### ISSUE TITLE
Memory leak with AnimatorListener

### ISSUE THREAD

**Issue by jordicapde** [bhargavms/DotLoader#7]
I have found a memory leak using the DotLoader library. I tried with a minimal case (which was a simple activity with a DotLoader) as a test and it happened too, so it seems to be a common issue.

My simple test case includes a single activity with a layout as follows:
```XML
<LinearLayout
   ...>

   <Button
      .../>

   <com.bhargavms.dotloader.DotLoader
      .../>

</LinearLayout>
```
And within the activity, the only thing that I'm doing is firing a new Intent to the same activity when I click the button. Whenever you click the button, the old activity is leaked.
I used LeakCanary and I copy a snapshot of the report:
![device-2017-05-19-144937](https://cloud.githubusercontent.com/assets/4255809/26300683/1e5275ea-3edf-11e7-9296-c5d7f810c7d4.png)

There seems to be something wrong with the AnimatorListeners which are added at _createValueAnimatorForDot_, but actually I don't know where the exact problem and solution are (maybe the listener shouldn't be instantiated anonymously, so it can be removed later).

**Comment by bhargavms** [comment]
I will look into it first thing when I get back from my home town tomorrow, I think what you said is right it's the anonymous classes capturing the view, I will also add leak canary to the sample app and run a test.

**Comment by bhargavms** [comment]
Also thank you for reporting it!

**Comment by bhargavms** [comment]
@jordicapde  This has been fixed in the linked commit, and in version 1.1.0  please take a look and confirm.

**Comment by jordicapde** [comment]
First of all, thanks for the speed in your answer @bhargavms.
I tried the new release and it doesn't seem to be enough to solve the problem.
Actually, LeakCanary is now reporting a different origin for the leak:
![device-2017-05-29-095037](https://cloud.githubusercontent.com/assets/4255809/26543070/c4e9f13a-445c-11e7-9066-e681a7c78bdd.png)

I don't have much experience implementing Android custom views but maybe the added listeners should be removed or cancelled when the view is detached (something like the code you have in _\_onStopAnimation()_)

**Comment by bhargavms** [comment]
Alright I will install leak canary in the sample app :\

**Comment by bhargavms** [comment]
@jordicapde have a look at the latest release, I have removed the mParent reference itself, and I have tested with LeakCanary, I am not able to see any leaks.

**Comment by jordicapde** [comment]
Yes, it seems that it's working properly now. Thank you again

**Comment by bhargavms** [comment]
thank you for reporting!
